// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: cryptodata.proto

/*
Package cryptodata_v1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package cryptodata_v1

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_CryptoDataService_GetTop50Coins_0(ctx context.Context, marshaler runtime.Marshaler, client CryptoDataServiceClient, req *http.Request, pathParams map[string]string) (CryptoDataService_GetTop50CoinsClient, runtime.ServerMetadata, error) {
	var protoReq GetCryptoCoinsRequest
	var metadata runtime.ServerMetadata

	stream, err := client.GetTop50Coins(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterCryptoDataServiceHandlerServer registers the http handlers for service CryptoDataService to "mux".
// UnaryRPC     :call CryptoDataServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterCryptoDataServiceHandlerFromEndpoint instead.
func RegisterCryptoDataServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server CryptoDataServiceServer) error {

	mux.Handle("GET", pattern_CryptoDataService_GetTop50Coins_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterCryptoDataServiceHandlerFromEndpoint is same as RegisterCryptoDataServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterCryptoDataServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterCryptoDataServiceHandler(ctx, mux, conn)
}

// RegisterCryptoDataServiceHandler registers the http handlers for service CryptoDataService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterCryptoDataServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterCryptoDataServiceHandlerClient(ctx, mux, NewCryptoDataServiceClient(conn))
}

// RegisterCryptoDataServiceHandlerClient registers the http handlers for service CryptoDataService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "CryptoDataServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "CryptoDataServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "CryptoDataServiceClient" to call the correct interceptors.
func RegisterCryptoDataServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client CryptoDataServiceClient) error {

	mux.Handle("GET", pattern_CryptoDataService_GetTop50Coins_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/cryptodata_v1.CryptoDataService/GetTop50Coins", runtime.WithHTTPPathPattern("/v1/cryptodata/get_top_50_coins"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CryptoDataService_GetTop50Coins_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_CryptoDataService_GetTop50Coins_0(annotatedContext, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_CryptoDataService_GetTop50Coins_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "cryptodata", "get_top_50_coins"}, ""))
)

var (
	forward_CryptoDataService_GetTop50Coins_0 = runtime.ForwardResponseStream
)
